version: '3'
services:
  web:
    build: .
    command: flatbot-run
    volumes:
    - ./src/flatbot/:/flatbot/src/flatbot
    environment:
      SCRAPER_FREQ: 10
      GOOGLE_APPLICATION_CREDENTIALS: /flatbot/cred.json
    depends_on:
      - postgres
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
