version: '3'
services:
  web:
    ports:
      - "192.168.100.106:8443:8443"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/db"
      PORT: 8443
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
