version: '3'
services:
  server:
    build: .
    command: bash /flatbot/scripts/run_server.sh
    ports:
      - "8443:8443"
    environment:
      SSL_PATH /flatbot/ssl/
    depends_on:
      - postgres
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
    - data/pgdata:/var/lib/postgresql/data/